[package]
name = "cities"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.8", features = ["derive"]}
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
